### ISSUE TITLE
Clan Ally Request spam

### ISSUE THREAD

**Issue by Mackaylie** [marcelo-mason/SimpleClans#408]
So on my server when one clan requested to ally another clan the requests get sent continuously until a restart of the server happens, wether the request was denied or accepted
I am unsure whats causing this and hoping someone can help me figure it out :D

**Comment by Gerolfing** [comment]
I have same isuue. I find out that plugin continue to send requests because it can't recodnize your unswer.. After typing /accept if player quits server plugin notifies that <player> has signed off. CREATE_ALLY request cancelled... So plugin didn't recodnize player's unswer in first place. Spam can be disabled by changing 
ask-frequency-secs: 60
to 
ask-frequency-secs: -1

**Comment by Gerolfing** [comment]
Looks like fixed in latest version on Jenkins
